name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tcl-tests-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update packages list
        run: sudo apt-get update

      - name: Install dependencies
        run: sudo apt-get install -y build-essential libtool autoconf automake tcl-dev

      - name: Test veryquick
        run: make -j $(nproc) && make veryquickcheck

      - name: Test full
        run: make -j $(nproc) && make check

      - name: Cleanup
        run: make clean