name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tcl-tests-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update packages list
        run: sudo apt-get update

      - name: Install dependencies
        run: sudo apt-get install -y build-essential libtool autoconf automake tcl-dev

      - name: Test veryquick
        run: |
          make -j $(nproc) && make veryquickcheck
          grep "errors out of" testrunner.log | awk -F" " '{if($1>0)exit 1}'

      - name: Test full
        run: |
          make -j $(nproc) && make check
          grep "errors out of" testrunner.log | awk -F" " '{if($1>0)exit 1}'

      - name: Failure Artifact
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: sqlsalt-failure
          path: |
            testrunner.db
            testrunner.log

      - name: Cleanup
        if: ${{ always() }}
        run: make clean
      